spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/users-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui